baseURL = 'https://lixozero.org.br/'
languageCode = 'pt-br'
title = 'Lixo Zero'
theme = 'lixo-zero'

[params]
  bannerSection = 'banners'
  homeSection = 'posts'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menus.main]]
name = 'Projeto'
url = '#projeto'
weight = 20

[[menus.main]]
name = 'Onde?'
url = '#onde'
weight = 30

[[menus.main]]
name = 'Como?'
url = '#como'
weight = 40

[[menus.main]]
name = 'Dicas'
url = '#'
weight = 50

[[menus.main]]
name = 'Impactos'
url = '#'
weight = 60

[[menus.main]]
name = 'Apoie'
url = '#apoie'
weight = 70

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
