baseURL = 'https://lixozero.org.br/'
languageCode = 'pt-br'
title = 'Lixo Zero'
theme = 'lixo-zero'

[params]
  bannerSection = 'banners'
  homeSection = 'posts'

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
